Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,29 +30,24 @@ jobs:
         cd react_app
         npm install
 
-    - name: Install react-scripts
-      run: |
-        cd react_app
-        npm install react-scripts
-
     - name: Build React app
       run: |
         cd react_app
         npm run build
+
+    - name: Verify Build Directory
+      run: |
+        ls -la react_app/build || echo "Build directory not found"
 
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.8'
 
-    - name: Install dependencies
+    - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-
-    - name: Install autopep8
-      run: |
-        pip install autopep8
 
     - name: Collect static files
       env:
@@ -60,16 +55,13 @@ jobs:
       run: |
         python manage.py collectstatic --noinput
 
-    - name: Run autopep8
+    - name: Run Python formatting and linting
       run: |
+        pip install autopep8 flake8
         find . -name "*.py" | xargs autopep8 --in-place --aggressive --aggressive
-
-    - name: Lint with flake8
-      run: |
-        pip install flake8
         flake8 .
 
-    - name: Run tests
+    - name: Run Django tests
       env:
         DJANGO_SETTINGS_MODULE: EmploymentAssessment.settings
       run: |
@@ -78,18 +70,13 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: build
-  
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
-  
+
     - name: Deploy to GitHub Pages
-      run: |
-        cd react_app/build
-        git init
-        git checkout --orphan gh-pages
-        git add .
-        git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m "Deploy to GitHub Pages"
-        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/nkzarrabi/Employment-Assessment.git" gh-pages:gh-pages
-
-
+      uses: peaceiris/actions-gh-pages@v3
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        publish_dir: react_app/build
